export const locationAreas = [
  {
    main: true,
    slug: "oldham",
    label: "Oldham",
    href: "/mobile-tyre-fitting-oldham",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "chadderton",
    label: "Chadderton",
    href: "/mobile-tyre-fitting-chadderton",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "royton",
    label: "Royton",
    href: "/mobile-tyre-fitting-royton",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "shaw",
    label: "Shaw",
    href: "/mobile-tyre-fitting-shaw",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "failsworth",
    label: "Failsworth",
    href: "/mobile-tyre-fitting-failsworth",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "saddleworth",
    label: "Saddleworth",
    href: "/mobile-tyre-fitting-saddleworth",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "uppermill",
    label: "Uppermill",
    href: "/mobile-tyre-fitting-uppermill",
    region: "Oldham & Saddleworth",
  },
  {
    main: true,
    slug: "manchester",
    label: "Manchester",
    href: "/mobile-tyre-fitting-manchester",
    region: "Manchester",
  },
  {
    main: true,
    slug: "manchester-city-centre",
    label: "Manchester City Centre",
    href: "/mobile-tyre-fitting-manchester-city-centre",
    region: "Manchester",
  },
  {
    slug: "ancoats",
    label: "Ancoats",
    href: "/mobile-tyre-fitting-ancoats",
    region: "Manchester",
  },
  {
    main: true,
    slug: "wythenshawe",
    label: "Wythenshawe",
    href: "/mobile-tyre-fitting-wythenshawe",
    region: "Manchester",
  },
  {
    slug: "cheetham-hill",
    label: "Cheetham Hill",
    href: "/mobile-tyre-fitting-cheetham-hill",
    region: "Manchester",
  },
  {
    slug: "blackley",
    label: "Blackley",
    href: "/mobile-tyre-fitting-blackley",
    region: "Manchester",
  },
  {
    slug: "chorlton",
    label: "Chorlton",
    href: "/mobile-tyre-fitting-chorlton",
    region: "Manchester",
  },
  {
    slug: "didsbury",
    label: "Didsbury",
    href: "/mobile-tyre-fitting-didsbury",
    region: "Greater Manchester East",
  },
  {
    slug: "gorton",
    label: "Gorton",
    href: "/mobile-tyre-fitting-gorton",
    region: "Greater Manchester East",
  },
  {
    slug: "longsight",
    label: "Longsight",
    href: "/mobile-tyre-fitting-longsight",
    region: "Greater Manchester East",
  },
  {
    slug: "moston",
    label: "Moston",
    href: "/mobile-tyre-fitting-moston",
    region: "Greater Manchester East",
  },
  {
    slug: "newton-heath",
    label: "Newton Heath",
    href: "/mobile-tyre-fitting-newton-heath",
    region: "Greater Manchester East",
  },
  {
    main: true,
    slug: "rochdale",
    label: "Rochdale",
    href: "/mobile-tyre-fitting-rochdale",
    region: "Greater Manchester East",
  },
  {
    slug: "middleton",
    label: "Middleton",
    href: "/mobile-tyre-fitting-middleton",
    region: "Rochdale North",
  },
  {
    slug: "heywood",
    label: "Heywood",
    href: "/mobile-tyre-fitting-heywood",
    region: "Rochdale North",
  },
  {
    slug: "littleborough",
    label: "Littleborough",
    href: "/mobile-tyre-fitting-littleborough",
    region: "Rochdale North",
  },
  {
    slug: "milnrow",
    label: "Milnrow",
    href: "/mobile-tyre-fitting-milnrow",
    region: "Rochdale North",
  },
  {
    main: true,
    slug: "bury",
    label: "Bury",
    href: "/mobile-tyre-fitting-bury",
    region: "Bury Area",
  },
  {
    slug: "prestwich",
    label: "Prestwich",
    href: "/mobile-tyre-fitting-prestwich",
    region: "Bury Area",
  },
  {
    slug: "whitefield",
    label: "Whitefield",
    href: "/mobile-tyre-fitting-whitefield",
    region: "Bury Area",
  },
  {
    slug: "radcliffe",
    label: "Radcliffe",
    href: "/mobile-tyre-fitting-radcliffe",
    region: "Bury Area",
  },
  {
    slug: "ramsbottom",
    label: "Ramsbottom",
    href: "/mobile-tyre-fitting-ramsbottom",
    region: "Bury Area",
  },
  {
    main: true,
    slug: "altrincham",
    label: "Altrincham",
    href: "/mobile-tyre-fitting-altrincham",
    region: "Trafford",
  },
  {
    slug: "sale",
    label: "Sale",
    href: "/mobile-tyre-fitting-sale",
    region: "Trafford",
  },
  {
    slug: "stretford",
    label: "Stretford",
    href: "/mobile-tyre-fitting-stretford",
    region: "Trafford",
  },
  {
    slug: "urmston",
    label: "Urmston",
    href: "/mobile-tyre-fitting-urmston",
    region: "Trafford",
  },
  {
    main: true,
    slug: "trafford-park",
    label: "Trafford Park",
    href: "/mobile-tyre-fitting-trafford-park",
    region: "Trafford",
  },
  {
    main: true,
    slug: "ashton-under-lyne",
    label: "Ashton-under-Lyne",
    href: "/mobile-tyre-fitting-ashton-under-lyne",
    region: "Tameside",
  },
  {
    slug: "audenshaw",
    label: "Audenshaw",
    href: "/mobile-tyre-fitting-audenshaw",
    region: "Tameside",
  },
  {
    slug: "dukinfield",
    label: "Dukinfield",
    href: "/mobile-tyre-fitting-dukinfield",
    region: "Tameside",
  },
  {
    slug: "hyde",
    label: "Hyde",
    href: "/mobile-tyre-fitting-hyde",
    region: "Tameside",
  },
  {
    slug: "stalybridge",
    label: "Stalybridge",
    href: "/mobile-tyre-fitting-stalybridge",
    region: "Tameside",
  },
  {
    slug: "mossley",
    label: "Mossley",
    href: "/mobile-tyre-fitting-mossley",
    region: "Tameside",
  },
  {
    slug: "eccles",
    label: "Eccles",
    href: "/mobile-tyre-fitting-eccles",
    region: "Salford",
  },
  {
    main: true,
    slug: "salford",
    label: "Salford",
    href: "/mobile-tyre-fitting-salford",
    region: "Salford",
  },
  {
    slug: "swinton",
    label: "Swinton",
    href: "/mobile-tyre-fitting-swinton",
    region: "Salford",
  },
  {
    slug: "walkden",
    label: "Walkden",
    href: "/mobile-tyre-fitting-walkden",
    region: "Salford",
  },
  {
    slug: "worsley",
    label: "Worsley",
    href: "/mobile-tyre-fitting-worsley",
    region: "Salford",
  },
  {
    slug: "irlam",
    label: "Irlam",
    href: "/mobile-tyre-fitting-irlam",
    region: "Salford",
  },
  {
    main: true,
    slug: "wigan",
    label: "Wigan",
    href: "/mobile-tyre-fitting-wigan",
    region: "Wigan Borough",
  },
  {
    slug: "leigh",
    label: "Leigh",
    href: "/mobile-tyre-fitting-leigh",
    region: "Wigan Borough",
  },
  {
    slug: "atherton",
    label: "Atherton",
    href: "/mobile-tyre-fitting-atherton",
    region: "Wigan Borough",
  },
  {
    slug: "tyldesley",
    label: "Tyldesley",
    href: "/mobile-tyre-fitting-tyldesley",
    region: "Wigan Borough",
  },
  {
    slug: "alderley-edge",
    label: "Alderley Edge",
    href: "/mobile-tyre-fitting-alderley-edge",
    region: "Cheshire",
  },
  {
    slug: "handforth",
    label: "Handforth",
    href: "/mobile-tyre-fitting-handforth",
    region: "Cheshire",
  },
  {
    slug: "knutsford",
    label: "Knutsford",
    href: "/mobile-tyre-fitting-knutsford",
    region: "Cheshire",
  },
  {
    main: true,
    slug: "macclesfield",
    label: "Macclesfield",
    href: "/mobile-tyre-fitting-macclesfield",
    region: "Cheshire",
  },
  {
    main: true,
    slug: "wilmslow",
    label: "Wilmslow",
    href: "/mobile-tyre-fitting-wilmslow",
    region: "Cheshire",
  },
  {
    slug: "bredbury",
    label: "Bredbury",
    href: "/mobile-tyre-fitting-bredbury",
    region: "Stockport",
  },
  {
    slug: "accrington",
    label: "Accrington",
    href: "/mobile-tyre-fitting-accrington",
    region: "East Lancashire",
  },
  {
    main: true,
    slug: "blackburn",
    label: "Blackburn",
    href: "/mobile-tyre-fitting-blackburn",
    region: "East Lancashire",
  },
  {
    main: true,
    slug: "burnley",
    label: "Burnley",
    href: "/mobile-tyre-fitting-burnley",
    region: "East Lancashire",
  },
  {
    slug: "colne",
    label: "Colne",
    href: "/mobile-tyre-fitting-colne",
    region: "East Lancashire",
  },
  {
    slug: "darwen",
    label: "Darwen",
    href: "/mobile-tyre-fitting-darwen",
    region: "East Lancashire",
  },
  {
    slug: "haslingden",
    label: "Haslingden",
    href: "/mobile-tyre-fitting-haslingden",
    region: "East Lancashire",
  },
  {
    slug: "nelson",
    label: "Nelson",
    href: "/mobile-tyre-fitting-nelson",
    region: "East Lancashire",
  },
  {
    slug: "rawtenstall",
    label: "Rawtenstall",
    href: "/mobile-tyre-fitting-rawtenstall",
    region: "East Lancashire",
  },
  {
    slug: "chorley",
    label: "Chorley",
    href: "/mobile-tyre-fitting-chorley",
    region: "Central Lancashire",
  },
  {
    main: true,
    slug: "preston",
    label: "Preston",
    href: "/mobile-tyre-fitting-preston",
    region: "Central Lancashire",
  },
  {
    main: true,
    slug: "bradford",
    label: "Bradford",
    href: "/mobile-tyre-fitting-bradford",
    region: "West Yorkshire",
  },
  {
    slug: "brighouse",
    label: "Brighouse",
    href: "/mobile-tyre-fitting-brighouse",
    region: "West Yorkshire",
  },
  {
    slug: "dewsbury",
    label: "Dewsbury",
    href: "/mobile-tyre-fitting-dewsbury",
    region: "West Yorkshire",
  },
  {
    main: true,
    slug: "halifax",
    label: "Halifax",
    href: "/mobile-tyre-fitting-halifax",
    region: "West Yorkshire",
  },
  {
    main: true,
    slug: "huddersfield",
    label: "Huddersfield",
    href: "/mobile-tyre-fitting-huddersfield",
    region: "West Yorkshire",
  },
  {
    slug: "congleton",
    label: "Congleton",
    href: "/mobile-tyre-fitting-congleton",
    region: "South Cheshire",
  },
  {
    slug: "crewe",
    label: "Crewe",
    href: "/mobile-tyre-fitting-crewe",
    region: "South Cheshire",
  },
  {
    slug: "holmes-chapel",
    label: "Holmes Chapel",
    href: "/mobile-tyre-fitting-holmes-chapel",
    region: "South Cheshire",
  },
  {
    slug: "nantwich",
    label: "Nantwich",
    href: "/mobile-tyre-fitting-nantwich",
    region: "South Cheshire",
  },
  {
    slug: "sandbach",
    label: "Sandbach",
    href: "/mobile-tyre-fitting-sandbach",
    region: "South Cheshire",
  },
  {
    main: true,
    slug: "bolton",
    label: "Bolton",
    href: "/mobile-tyre-fitting-bolton",
    region: "Bolton Area",
  },
  {
    slug: "farnworth",
    label: "Farnworth",
    href: "/mobile-tyre-fitting-farnworth",
    region: "Bolton Area",
  },
  {
    slug: "horwich",
    label: "Horwich",
    href: "/mobile-tyre-fitting-horwich",
    region: "Bolton Area",
  },
  {
    slug: "westhoughton",
    label: "Westhoughton",
    href: "/mobile-tyre-fitting-westhoughton",
    region: "Bolton Area",
  },
  {
    main: true,
    slug: "stockport",
    label: "Stockport",
    href: "/mobile-tyre-fitting-stockport",
    region: "Stockport",
  },
  {
    slug: "cheadle",
    label: "Cheadle",
    href: "/mobile-tyre-fitting-cheadle",
    region: "Stockport",
  },
  {
    slug: "cheadle-hulme",
    label: "Cheadle Hulme",
    href: "/mobile-tyre-fitting-cheadle-hulme",
    region: "Stockport",
  },
  {
    slug: "bramhall",
    label: "Bramhall",
    href: "/mobile-tyre-fitting-bramhall",
    region: "Stockport",
  },
  {
    slug: "hazel-grove",
    label: "Hazel Grove",
    href: "/mobile-tyre-fitting-hazel-grove",
    region: "Stockport",
  },
  {
    slug: "reddish",
    label: "Reddish",
    href: "/mobile-tyre-fitting-reddish",
    region: "Stockport",
  },
  {
    slug: "marple",
    label: "Marple",
    href: "/mobile-tyre-fitting-marple",
    region: "Stockport",
  },
  {
    slug: "denton",
    label: "Denton",
    href: "/mobile-tyre-fitting-denton",
    region: "Tameside",
  },
  {
    slug: "droylsden",
    label: "Droylsden",
    href: "/mobile-tyre-fitting-droylsden",
    region: "Tameside",
  },
  {
    slug: "poynton",
    label: "Poynton",
    href: "/mobile-tyre-fitting-poynton",
    region: "Cheshire",
  },
  {
    main: true,
    slug: "warrington",
    label: "Warrington",
    href: "/mobile-tyre-fitting-warrington",
    region: "Warrington & Halton",
  },
  {
    slug: "lymm",
    label: "Lymm",
    href: "/mobile-tyre-fitting-lymm",
    region: "Warrington & Halton",
  },
  {
    slug: "stockton-heath",
    label: "Stockton Heath",
    href: "/mobile-tyre-fitting-stockton-heath",
    region: "Warrington & Halton",
  },
  {
    slug: "birchwood",
    label: "Birchwood",
    href: "/mobile-tyre-fitting-birchwood",
    region: "Warrington & Halton",
  },
  {
    main: true,
    slug: "runcorn",
    label: "Runcorn",
    href: "/mobile-tyre-fitting-runcorn",
    region: "Warrington & Halton",
  },
  {
    main: true,
    slug: "widnes",
    label: "Widnes",
    href: "/mobile-tyre-fitting-widnes",
    region: "Warrington & Halton",
  },
  {
    slug: "northwich",
    label: "Northwich",
    href: "/mobile-tyre-fitting-northwich",
    region: "South Cheshire",
  },
  {
    slug: "middlewich",
    label: "Middlewich",
    href: "/mobile-tyre-fitting-middlewich",
    region: "South Cheshire",
  },
  {
    slug: "winsford",
    label: "Winsford",
    href: "/mobile-tyre-fitting-winsford",
    region: "South Cheshire",
  },
  {
    main: true,
    slug: "wakefield",
    label: "Wakefield",
    href: "/mobile-tyre-fitting-wakefield",
    region: "West Yorkshire",
  },
] as const;

export const locationAreasByRegion = Array.from(
  locationAreas.reduce((map, area) => {
    const group = map.get(area.region) ?? [];
    group.push(area);
    map.set(area.region, group);
    return map;
  }, new Map<string, (typeof locationAreas)[number][]>()),
  ([region, areas]) => ({ region, areas }),
);

// The primary hub towns (one per major coverage cluster) shown in the header
// mega menu — the full 100-location list lives on the /areas-we-cover page.
export const locationAreasMain = locationAreas.filter((area) => "main" in area && area.main);
