export const locationAreas = [
  { slug: "oldham", label: "Oldham", href: "/mobile-tyre-fitting-oldham", region: "Oldham & Saddleworth" },
  {
    slug: "chadderton",
    label: "Chadderton",
    href: "/mobile-tyre-fitting-chadderton",
    region: "Oldham & Saddleworth",
  },
  { slug: "royton", label: "Royton", href: "/mobile-tyre-fitting-royton", region: "Oldham & Saddleworth" },
  { slug: "shaw", label: "Shaw", href: "/mobile-tyre-fitting-shaw", region: "Oldham & Saddleworth" },
  {
    slug: "failsworth",
    label: "Failsworth",
    href: "/mobile-tyre-fitting-failsworth",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "saddleworth",
    label: "Saddleworth",
    href: "/mobile-tyre-fitting-saddleworth",
    region: "Oldham & Saddleworth",
  },
  {
    slug: "uppermill",
    label: "Uppermill",
    href: "/mobile-tyre-fitting-uppermill",
    region: "Oldham & Saddleworth",
  },
  { slug: "manchester", label: "Manchester", href: "/mobile-tyre-fitting-manchester", region: "Manchester" },
  {
    slug: "manchester-city-centre",
    label: "Manchester City Centre",
    href: "/mobile-tyre-fitting-manchester-city-centre",
    region: "Manchester",
  },
  { slug: "ancoats", label: "Ancoats", href: "/mobile-tyre-fitting-ancoats", region: "Manchester" },
  {
    slug: "wythenshawe",
    label: "Wythenshawe",
    href: "/mobile-tyre-fitting-wythenshawe",
    region: "Manchester",
  },
  {
    slug: "cheetham-hill",
    label: "Cheetham Hill",
    href: "/mobile-tyre-fitting-cheetham-hill",
    region: "Manchester",
  },
  { slug: "blackley", label: "Blackley", href: "/mobile-tyre-fitting-blackley", region: "Manchester" },
  { slug: "chorlton", label: "Chorlton", href: "/mobile-tyre-fitting-chorlton", region: "Manchester" },
  {
    slug: "didsbury",
    label: "Didsbury",
    href: "/mobile-tyre-fitting-didsbury",
    region: "Greater Manchester East",
  },
  { slug: "gorton", label: "Gorton", href: "/mobile-tyre-fitting-gorton", region: "Greater Manchester East" },
  {
    slug: "longsight",
    label: "Longsight",
    href: "/mobile-tyre-fitting-longsight",
    region: "Greater Manchester East",
  },
  { slug: "moston", label: "Moston", href: "/mobile-tyre-fitting-moston", region: "Greater Manchester East" },
  {
    slug: "newton-heath",
    label: "Newton Heath",
    href: "/mobile-tyre-fitting-newton-heath",
    region: "Greater Manchester East",
  },
  {
    slug: "rochdale",
    label: "Rochdale",
    href: "/mobile-tyre-fitting-rochdale",
    region: "Greater Manchester East",
  },
  {
    slug: "middleton",
    label: "Middleton",
    href: "/mobile-tyre-fitting-middleton",
    region: "Rochdale North",
  },
  { slug: "heywood", label: "Heywood", href: "/mobile-tyre-fitting-heywood", region: "Rochdale North" },
  {
    slug: "littleborough",
    label: "Littleborough",
    href: "/mobile-tyre-fitting-littleborough",
    region: "Rochdale North",
  },
  { slug: "milnrow", label: "Milnrow", href: "/mobile-tyre-fitting-milnrow", region: "Rochdale North" },
  { slug: "bury", label: "Bury", href: "/mobile-tyre-fitting-bury", region: "Bury Area" },
  { slug: "prestwich", label: "Prestwich", href: "/mobile-tyre-fitting-prestwich", region: "Bury Area" },
  { slug: "whitefield", label: "Whitefield", href: "/mobile-tyre-fitting-whitefield", region: "Bury Area" },
  { slug: "radcliffe", label: "Radcliffe", href: "/mobile-tyre-fitting-radcliffe", region: "Bury Area" },
  {
    slug: "ramsbottom",
    label: "Ramsbottom",
    href: "/mobile-tyre-fitting-ramsbottom",
    region: "Bury Area",
  },
  { slug: "altrincham", label: "Altrincham", href: "/mobile-tyre-fitting-altrincham", region: "Trafford" },
  { slug: "sale", label: "Sale", href: "/mobile-tyre-fitting-sale", region: "Trafford" },
  { slug: "stretford", label: "Stretford", href: "/mobile-tyre-fitting-stretford", region: "Trafford" },
  { slug: "urmston", label: "Urmston", href: "/mobile-tyre-fitting-urmston", region: "Trafford" },
  {
    slug: "trafford-park",
    label: "Trafford Park",
    href: "/mobile-tyre-fitting-trafford-park",
    region: "Trafford",
  },
  {
    slug: "ashton-under-lyne",
    label: "Ashton-under-Lyne",
    href: "/mobile-tyre-fitting-ashton-under-lyne",
    region: "Tameside",
  },
  { slug: "audenshaw", label: "Audenshaw", href: "/mobile-tyre-fitting-audenshaw", region: "Tameside" },
  { slug: "dukinfield", label: "Dukinfield", href: "/mobile-tyre-fitting-dukinfield", region: "Tameside" },
  { slug: "hyde", label: "Hyde", href: "/mobile-tyre-fitting-hyde", region: "Tameside" },
  {
    slug: "stalybridge",
    label: "Stalybridge",
    href: "/mobile-tyre-fitting-stalybridge",
    region: "Tameside",
  },
  { slug: "mossley", label: "Mossley", href: "/mobile-tyre-fitting-mossley", region: "Tameside" },
  { slug: "eccles", label: "Eccles", href: "/mobile-tyre-fitting-eccles", region: "Salford" },
  { slug: "salford", label: "Salford", href: "/mobile-tyre-fitting-salford", region: "Salford" },
  { slug: "swinton", label: "Swinton", href: "/mobile-tyre-fitting-swinton", region: "Salford" },
  { slug: "walkden", label: "Walkden", href: "/mobile-tyre-fitting-walkden", region: "Salford" },
  { slug: "worsley", label: "Worsley", href: "/mobile-tyre-fitting-worsley", region: "Salford" },
  { slug: "irlam", label: "Irlam", href: "/mobile-tyre-fitting-irlam", region: "Salford" },
  { slug: "wigan", label: "Wigan", href: "/mobile-tyre-fitting-wigan", region: "Wigan Borough" },
  { slug: "leigh", label: "Leigh", href: "/mobile-tyre-fitting-leigh", region: "Wigan Borough" },
  { slug: "atherton", label: "Atherton", href: "/mobile-tyre-fitting-atherton", region: "Wigan Borough" },
  {
    slug: "tyldesley",
    label: "Tyldesley",
    href: "/mobile-tyre-fitting-tyldesley",
    region: "Wigan Borough",
  },
  {
    slug: "alderley-edge",
    label: "Alderley Edge",
    href: "/mobile-tyre-fitting-alderley-edge",
    region: "Cheshire",
  },
  { slug: "handforth", label: "Handforth", href: "/mobile-tyre-fitting-handforth", region: "Cheshire" },
  { slug: "knutsford", label: "Knutsford", href: "/mobile-tyre-fitting-knutsford", region: "Cheshire" },
  {
    slug: "macclesfield",
    label: "Macclesfield",
    href: "/mobile-tyre-fitting-macclesfield",
    region: "Cheshire",
  },
  { slug: "wilmslow", label: "Wilmslow", href: "/mobile-tyre-fitting-wilmslow", region: "Cheshire" },
  { slug: "bredbury", label: "Bredbury", href: "/mobile-tyre-fitting-bredbury", region: "Stockport" },
] as const;

export const locationAreasByRegion = Array.from(
  locationAreas.reduce((map, area) => {
    const group = map.get(area.region) ?? [];
    group.push(area);
    map.set(area.region, group);
    return map;
  }, new Map<string, (typeof locationAreas)[number][]>()),
  ([region, areas]) => ({ region, areas }),
);
